# Generated by Django 4.0.4 on 2022-07-15 13:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_fa', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('summery', ckeditor.fields.RichTextField()),
                ('summery_fa', ckeditor.fields.RichTextField(null=True)),
                ('summery_en', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(upload_to='news-images/%Y/%m/%d/')),
                ('body', ckeditor.fields.RichTextField()),
                ('body_fa', ckeditor.fields.RichTextField(null=True)),
                ('body_en', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
