# Generated by Django 4.0.4 on 2022-07-15 09:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summery', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='news-images/%Y/%m/%d/')),
                ('body', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
