# Generated by Django 4.0.4 on 2022-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='hello', max_length=250)),
                ('summery', models.TextField()),
                ('main_image', models.ImageField(upload_to='news-images/')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
