# Generated by Django 3.2.5 on 2022-07-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='media/news-images/yes.png', upload_to='news-images/'),
        ),
    ]
