# Generated by Django 4.0.4 on 2022-07-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_body_alter_news_summery'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default='2012-09-04 06:00:00.000000-08:00'),
        ),
    ]
