# Generated by Django 4.0.4 on 2022-07-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created',
        ),
    ]
