# Generated by Django 4.0.4 on 2022-07-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='main_image',
        ),
    ]
