# Generated by Django 4.0.4 on 2022-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_rename_image_news_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='summery',
            field=models.TextField(),
        ),
    ]
