# Generated by Django 4.0.4 on 2022-04-29 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mr_dr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrdr',
            old_name='body',
            new_name='question',
        ),
        migrations.AddField(
            model_name='mrdr',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
