# Generated by Django 4.0.4 on 2022-04-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_dr', '0002_rename_body_mrdr_question_mrdr_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrdr',
            name='created',
            field=models.DateField(),
        ),
    ]
