# Generated by Django 4.0.4 on 2022-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_dr', '0004_remove_mrdr_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrdr',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
